### ISSUE TITLE
Windows newlines in 1.2.0 packaged index.js

### ISSUE THREAD

**Issue by asmundg** [milewski/cross-os#10]
It seems like the 1.2.0 version of cross-os has windows newlines in index.js, causing execution to fail on non-Windows platforms.

Did you happen to do the publish from a Windows box without fixing the line endings first? :)

**Comment by milewski** [comment]
how come? the tests did pass on travis mac and linux https://travis-ci.org/milewski/cross-os

**Comment by asmundg** [comment]
The line endings will reflect the system the files are checked out on, depending on git config. I'm guessing you're publishing manually after building on a windows box, in which case you may get windows line endings.

The tests will pass because 1) Travis gets normal line endings when checking out the files or 2) none of the tests actually invoke the shebang expression, since they all run 'node source/index.js'.

You may want to look at having Travis autodeploy for you: https://docs.travis-ci.com/user/deployment/npm/.

**Comment by Electr0n** [comment]
As I understood I had same issue.
In my package.json devDependency **"cross-os": "^1.2.0"**
When I'm trying to [npm run foo](https://github.com/milewski/cross-os#usage) I got an error:
/usr/bin/env: ‘node\r’: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! app@1.0.0 foo: `cross-os bar`
npm ERR! spawn ENOENT

**4-5 hours of deep magic solved my issue:**
1. rm -rf node_modules/
2. npm install
3. cd node_modules/cross-os/
4. I used dos2unix for each file from this and included dirs
5. in my app directory npm run foo => success

Looks like somewhere in node_modules/cross-os/ for version 1.2.0 you have /r symbol

**UPDATE:**
Also **"cross-os": 1.1.2** in my package.json fix my problems

**Comment by milewski** [comment]
Okay i found the issue...

git auto converts **CRLF** to **LF** when i push to github, and it also auto converts **LF** to **CRLF** when i clone locally on a windows machine...  so all my local files were using **CRLF**, which when i publish to NPM doesnt benefits from this auto conversion thing.....

so i have added a `.gitattributes` that forces all my local files to be **LF** so no more issues here i guess...

i have published a new version can you guys test to see if its working on UNIX?

**Comment by Electr0n** [comment]
No, sorry. Same issue.
1) rm -rf node_modules/
2) npm install
3) npm run foo

/usr/bin/env: ‘node\r’: No such file or directory
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

dos2unix for node_modules/cross-os/ help me again

**Comment by milewski** [comment]
okay now i totally got it.... the issue now was... the source file `.ts` was on the right file ending **LF** however typescript was compiling the js using the underlying OS line ending... so... the **.js** was being emitted as **CRLF**

..luckily there is an option on the **.tsconfig** to specify that i wanna **LF**

it should be working now.. can you test again?

**Comment by Electr0n** [comment]
Yes. Work for me. Thanks!

**Comment by milewski** [comment]
Great! 👍
