### ISSUE TITLE
Passing parameters to scripts

### ISSUE THREAD

**Issue by avner-hoffmann** [milewski/cross-os#15]
Hi,
Is there a way to pass parameters to the scripts within the cross-os: platform?
e.g.
 
"scripts": {
  "foo": "cross-os bar"
}
"cross-os": {
  "bar": {
    "darwin": "echo $1", // will print 'Running on darwin'
  }
}

npm run foo -- "Running on darwin"

**Comment by milewski** [comment]
Sorry i didn't thought on this when i created this lib.. this script only has 51 lines.. should be very simple to modify it... perhaps you could send a PR suggesting this improvement?

**Comment by avner-hoffmann** [comment]
Hi, I cloned the repo and adjusted the script to work with parameters
I'm sending you a private message...

**Comment by milewski** [comment]
i have replied that @avner-hoffmann 👍
