### ISSUE TITLE
Alternative to 'scripts' member in package.json

### ISSUE THREAD

**Issue by flcdrg** [milewski/cross-os#23]
Thanks for a very useful package!

I use VSCode, and it it validating my package.json file against the schema in http://json.schemastore.org/project.

This flags the {} block added to `scripts` with a warning, as it is only expecting strings.

Would it be possible to have as an alternative a separate top-level member (eg. `cross-os`) that could also be used to define the cross-os scripts? This way, it would not trigger schema violations (for people that worry about that kind of thing!).

Something like:

```
  "scripts": {
    "clean": "cross-os clean-platform"
  },
  "cross-os": {
    "clean-platform": {
      "win32": "del /s /q dist",
      "darwin:linux": "rm -rf dist"
    }
  },
```

**Comment by milewski** [comment]
Hey @flcdrg I got you covered! I feel the same when IDEs starts complaining for these kind of things too, however you already posted the solution! on the readme I have this:

```
Alternatively you can also specify scripts on its own section in your package.json

"scripts": {
  "foo": "cross-os bar"
}
"cross-os": {
  "bar": {
    "darwin": "echo 'i will only run on Mac'",
    "win32": "echo 'i will only run on Windows'",
    "linux": "echo 'i will only run on Linux'"
  }
}
```

Therefore the example you posted should be already working! let me know if it doesn't!

**Comment by flcdrg** [comment]
Ha, that's hilarious - I totally missed that!

Great minds think alike 😃
