### ISSUE TITLE
For multiple Command

### ISSUE THREAD

**Issue by shidandev** [milewski/cross-os#30]
@milewski can you help me for this script example, i want to run "nodemon --exec python index.py" then "ionic serve", but nodemon part only execute and ionic part nothing happened

`{
 "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint",
    "eel":"cross-os eel1"
 
  },
  "cross-os":{
    "eel1": {
      "darwin":"nodemon --exec python3 index.py && ionic serve",
      "win32": "nodemon --exec python index.py && ionic serve "
    }
  },
}`

**Comment by milewski** [comment]
I think the reason is that nodemon never exit, it probably is running in the foreground and never releases the handle for the `&& ionic server` part to run.. my guess is you could `nodemon --exec python index.py & && ionic serve`
