### ISSUE TITLE
Yarn?

### ISSUE THREAD

**Issue by ahj** [milewski/cross-os#6]
Am I wrong to wish this would work under Yarn?
```
TypeError: Cannot convert object to primitive value
      at /usr/share/yarn/lib/yarn-cli.js:77863:42
      at next (native)
      at step (/usr/share/yarn/lib/yarn-cli.js:91:30)
      at /usr/share/yarn/lib/yarn-cli.js:109:14
      at Promise.F (/usr/share/yarn/lib/yarn-cli.js:29304:28)
      at /usr/share/yarn/lib/yarn-cli.js:88:12
      at runCommand (/usr/share/yarn/lib/yarn-cli.js:77888:22)
      at Object.<anonymous> (/usr/share/yarn/lib/yarn-cli.js:77939:14)
      at next (native)
      at step (/usr/share/yarn/lib/yarn-cli.js:91:30)
```

**Comment by milewski** [comment]
I haven't tested it with yarn!!... but let me have a look what i can do..

**Comment by milewski** [comment]
i just tested it with `yarn run command-name` and it seem to work... are you sure the error isnt comming from your script? look my output: 

![image](https://user-images.githubusercontent.com/2874967/28626159-d4276b92-7250-11e7-9ea4-7d0c52e76363.png)


```json
"scripts":{
  "try": "cross-os test-it",
  "test-it": {
    "win32": "echo 'it works'"
  }
}
```

**Comment by ahj** [comment]
Thank you so much for responding.
The script definitions you used above work for me - so I have a path forward!

The example given in the readme didn't work without adding a "try": "cross-os bar".

**Comment by milewski** [comment]
`try` could be any name.... you just need to double check if you weren't naming the keys with the same name for example:

```json
"scripts": {
  "bar": "cross-os bar",
  "bar": {
    "darwin": "echo 'i will only run on Mac'",
    "win32": "echo 'i will only run on Windows'",
    "linux": "echo 'i will only run on Linux'"
  }
}
```
`yarn run bar` this wouldnt work because, the second bar would override the first `bar` so to fix this you need to change the name of the second `"bar"` 


this works 👍 

```json
"scripts": {
  "bar": "cross-os DIFFERENT_NAME",
  "DIFFERENT_NAME": {
    "darwin": "echo 'i will only run on Mac'",
    "win32": "echo 'i will only run on Windows'",
    "linux": "echo 'i will only run on Linux'"
  }
}
```
